version: "3"

services:
  studio-lite-db:
    container_name: studio-lite-db
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    volumes:
      - /data/postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql